### ISSUE TITLE
HStack

### ISSUE THREAD

**Issue by Nycolaide** [Nycolaide/manakit#2]
## Feature
Module name: **HStack**
Module parent: --

### Description
HStack aims to provide visual rendering with horizontal scrolling with the mouse or touch.
It allows you to display a list with immediate rendering.

### Requirement Dev

- [ ] The height is based on the tallest child
- [ ] The left action button shows if the child is 1 or more
- [ ] The right action button shows if the child is last -1 
- [ ] Buttons only show when pointer is in HStack display area
- [ ] No Button is displayed if the total size is less than the size of the display area
- [ ] You can customize the icon of the buttons

**Comment by Nycolaide** [comment]
![Capture d’écran 2022-06-22 à 10 17 06](https://user-images.githubusercontent.com/62988176/174984566-0bb09029-de69-449c-8234-7192cb338981.png)
